### PR TITLE
add pull_request cromwell and wom ghas

### PR DESCRIPTION
**Pull request by seankross**
I feel like we should at least be running the "compute happens on gha exclusively" tests for every PR.

### CODE REVIEW

**Comment by sckott** [comment]
Yes in theory - though ideally tests run really fast to get fast feedback from CI. Looks like the womtool stuff runs fast, but the cromwell test runs looks like it's already near 2 min in runtime with 3 files. Could that be sped up at all

**Comment by tefirman** [comment]
> cromwell test runs looks like it's already near 2 min in runtime with 3 files. Could that be sped up at all

Not that I can see, this is as bare bones as it gets. The only other thing I can think of is trying miniWDL as opposed to Cromwell, but that feels like it would defeat the purpose of trying to be as apples-to-apples as possible with PROOF..

**Comment by tefirman** [comment]
Here's an equivalent GitHub Action yml using miniwdl: https://github.com/openwdl/workflow-template-wdl/blob/main/.github/workflows/unit.yml

**Comment by seankross** [comment]
`&` lets us run each cromwell command in the background. Cut the time in half, for now. I'm not sure if this will stay constant-ish time or grow linearly as we add unit tests: https://github.com/FredHutch/wdl-unit-tests/pull/22/commits/e987b88d0d092ed520913cbac3bdbae7c7d3726c

**Review by tefirman — APPROVED** [review]
Great call, @seankross ! Looks good to me, but like you said, let's keep an eye on this timing as we add more unit-tests. I'll make sure to incorporate the yml updates into my two existing PR's.

**Comment by sckott** [comment]
perhaps we want to make sure these actions run only on PRs that originate from branches within the repo? or maybe not?  e.g., 
https://github.com/getwilds/.github/blob/main/workflow-templates/deploy-preview.yml#L27

**Comment by tefirman** [comment]
@sckott -- seems smart to me, just added that condition to both YML files.

**Comment by sckott** [comment]
cool i'll add to the api tests one as well

**Pull request closed without merging**
